### ISSUE TITLE
Symfony configuration

### ISSUE THREAD

**Issue by nennad** [maxbanton/cwh#10]
Hi there,

We would like to use this package in our Symfony project. Is there a chance that you have an example configuration for Symfony?

Many thanks!

**Comment by vurcease** [comment]
I would be interested in the same, as well. We're currently using an .ebextensions configuration to stream the Symfony logs to CloudWatch Logs, but it would be beneficial to stream specific log writes to CloudWatch directly. I started following this project with the intent to come back around to just this utilization.

**Comment by nennad** [comment]
Hi @vurcease, we figured it out.

So in your config.yml you need something like this:
`
monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      custom
        custom:
            type: service
            id: cloudwatch_handler
`

Then in services.yml put this:
`
    cloudwatch_client:
        class: Aws\CloudWatchLogs\CloudWatchLogsClient
        arguments:
            -
                credentials: { key: "%amazon_accesskey%", secret: "%amazon_secretkey%" }
                region: "%amazon_region%"
                version: "2014-03-28"

    cloudwatch_handler:
        class: Maxbanton\Cwh\Handler\CloudWatch
        arguments:
            - "@cloudwatch_client"
            - "my_group_name"              # groupName
            - "%kernel.environment%" # streamName
            - 30                     # retentionDays
            - 10000                  # logsInBatch
            - { mytag: "tag" }       # tags
            - WARNING                # logLevel
`

In addition to this package you also need this:
`
composer require aws/aws-sdk-php
`

Hope this helps.

**Comment by maxbanton** [comment]
Hi!
Thanks @nennad for your posting!
Actually, last step

> In addition to this package you also need this:
>```
> composer require aws/aws-sdk-php
>```

is not needed, AWS SDK is already required by library.

**Comment by nennad** [comment]
You're right @maxbanton ! Thanks for the nice lib btw 🥇 🍻

**Comment by maxbanton** [comment]
@nennad you are welcome!

**Comment by mikemix** [comment]
Would love to see [the example](https://github.com/maxbanton/cwh/issues/10#issuecomment-296173601) upgraded so that an additional file handler also keeps the logs in case there were some connection issues with the CloudWatch.

**Comment by ryancastle** [comment]
@mikemix I think the standard grouping mechanism would work fine.

```
monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      grouped
        grouped:
            type:    group
            members: [local, cloudwatch]
        local:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
        cloudwatch:
            type: service
            id: cloudwatch_handler
```

**Comment by Slowwie** [comment]
Omg, I thank u so much. This solved this issue for me so fast. Thought that will be hard work. But its was a joke so easy ;)! Thanks Guys.

**Comment by 24HOURSMEDIA** [comment]
Note that the above configuration only logs the 'errors' or 'critical' logs to CloudWatch.
This is because the 'local' handler apparently removes the 'debug and notice' levels.

if you want to log debug and notice levels too, change. to:

```
grouped:
            type:    group
            members: [cloudwatch,local]
```
