### ISSUE TITLE
[FEATURE] Support PHP 8.x

### ISSUE THREAD

**Issue by reactjs-net-au** [maxbanton/cwh#104]
**Is your feature request related to a problem? Please describe.**

No, cwh package requires php ^7.2 and my php version (8.1.2) does not satisfy the requirement.

**Describe the solution you'd like**

Apparently works on php 8, any reason why not 8.x?  Up to the latest PHP 8 release?

Has anyone tried using it with the latest versions of PHP?  I'm not sure why only PHP 8 is listed, surely it would not fail (silently or not) on PHP 8.1.2 for example.

**Comment by sebaguette** [comment]
I ran into the same problem ... but cwh package DOES support PHP 8, as of 2.0.2

How is your cwh package declared ? It should be
`"maxbanton/cwh": "^2.0"`
and not
`"maxbanton/cwh": "2.0"`

**Comment by ecomleader** [comment]
@sebaguette I upgraded to version 2.0.2 and now it works. Thanks

**Comment by maxbanton** [comment]
8.0 is already supported, for >=8.1 some amount of work is needed, not sure when it can be done. Maybe somebody wants to create a pull request?
