### ISSUE TITLE
initialize must throw exceptions if something failed

### ISSUE THREAD

**Issue by cyrilhamidechi** [maxbanton/cwh#11]
Hi,

First of all thank you for this useful handler recently discovered through this [article](https://aws.amazon.com/blogs/developer/php-application-logging-with-amazon-cloudwatch-logs-and-monolog/) ;)

One improvement might be that initialize could throw exceptions if something failed, especially if client is not allowed to perform some actions.

It happens to me while I'm trying using it with a user having the permission of [AWSOpsWorksCloudWatchLogs](http://docs.aws.amazon.com/opsworks/latest/userguide/monitoring-cloudwatch-logs.html).
The absence of any return from the script make me putting some `var_dump` & cie into the handler until finding what went wrong.
Solution was to basically grant user with permission CloudWatchLogsFullAccess for make it work.

Best regards,

Cyril

**Comment by maxbanton** [comment]
Hi, Cyril!
Thanks for your feedback!

From my prospective it's not the best solution to throw Exceptions inside initialize method, there are some chance that application (or request to the application) will fail because of Exception.

But, definitely it should be improved. Will look into it.

Regards,
Max.

**Comment by cwhittl** [comment]
I think my issue is related to this but I've configured my laravel app using this https://aws.amazon.com/blogs/developer/php-application-logging-with-amazon-cloudwatch-logs-and-monolog/ as a "walkthrough" and nothing errors but nothing reports in Cloudwatch either.
`$app->configureMonologUsing(
        function ($monolog) {
            //Local logs due to CW isn't working
            $monolog->pushHandler(new StreamHandler(storage_path('/logs/laravel.log')));

            $cwClient = App::make('aws')->createClient('CloudWatchLogs');
            $cwGroupName = env('AWS_CWL_GROUP', 'web_apps');
            $cwStreamNameApp = env('AWS_CWL_APP', 'zsync');
            $cwTagName = env('AWS_CWL_TAG_NAME', 'environment');
            $cwTagValue = env('AWS_CWL_TAG_VALUE', env('APP_ENV'));
            $cwRetentionDays = env('AWS_CWL_RETENTION', 90);
            $cwHandlerApp = new CloudWatch($cwClient, $cwGroupName, $cwStreamNameApp, $cwRetentionDays, 10000, [ $cwTagName => $cwTagValue ]);

            $monolog->pushHandler($cwHandlerApp);
        }
    );`

Is there anyway to debug?
Thanks!

**Comment by maxbanton** [comment]
Application should handle all exception types, it makes no sense to catch and then throw exceptions in the handler. Also, handler should know nothing about permissions configuration inside AWS account.
Closed.
