### ISSUE TITLE
AWS permission requirements

### ISSUE THREAD

**Issue by cyrilhamidechi** [maxbanton/cwh#12]
Hi again,

Another issue, related to the previous one :)

Is this handler really need such extensive permission like CloudWatchLogsFullAccess?
Or could [AWSOpsWorksCloudWatchLogs](http://docs.aws.amazon.com/opsworks/latest/userguide/monitoring-cloudwatch-logs.html) be sufficient?
Particularly it allows to create groups, streams and put log events, which seems cover the needs of this handler.

Best regards,

Cyril

**Comment by maxbanton** [comment]
Hi, Cyril!
Actually, handler knows nothing about permissions and you should setup proper rights by your own.
Here is a list of API calls that handler should be able to do:
 - DescribeLogGroups
 - CreateLogGroup
 - PutRetentionPolicy
 - DescribeLogStreams
 - CreateLogStream
 - putLogEvents

You can follow [this documentation](http://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_Operations.html) for more details regarding API calls and [this one](http://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/iam-identity-based-access-control-cwl.html) for details about Identity-Based Policies.

Regards,
Max.

**Comment by cyrilhamidechi** [comment]
Thank you for your answer Max
