### ISSUE TITLE
Suggestion - it will be possible to omit calls to describeLogStreams, which by default limited to 5 reqs per second

### ISSUE THREAD

**Issue by anxhelo15** [maxbanton/cwh#121]
Just a quick comment - proposed PR would be a very nice addition, as it will be possible to omit calls to describeLogStreams, which by default limited to 5 reqs per second

_Originally posted by @A-Shevchenko in https://github.com/maxbanton/cwh/issues/115#issuecomment-1456368141_

**Comment by markinjapan** [comment]
@anxhelo15 Please see v3.1.0 of this fork:
https://github.com/phpnexus/cwh/releases/tag/v3.1.0

I've incorporated a change that allows setting `$createStream` to `false` to prevent calling `describeLogStreams`.

**Comment by anxhelo15** [comment]
Thanks a lot Mark, it did work
