### ISSUE TITLE
Handle microseconds on timestamp

### ISSUE THREAD

**Issue by cyrilhamidechi** [maxbanton/cwh#13]
Time-close logs are not properly ordered when store on CWL because of `*1000` on https://github.com/maxbanton/cwh/blob/master/src/Handler/CloudWatch.php#L173

Maybe a 
`'timestamp' => explode('.', $entry['datetime']->format('U.u') * 1000)[0]`
would be better ?

**Comment by maxbanton** [comment]
Hi @cyrilhamidechi!
Should be fixed in latest version 1.1.1.
Please update and test it.
Thanks.

**Comment by cyrilhamidechi** [comment]
Thanks a lot @maxbanton 
Will try as soon as I can
Best
