### ISSUE TITLE
AWS API limit exceeded errors

### ISSUE THREAD

**Issue by cjunge-work** [maxbanton/cwh#14]
When using the log handler to send logs from queue workers to AWS, we often get a throttle error due to exceeding an API limit. AWS Support beleive it is the DescribeLogGroups API that is being throttled.

The `initialize` method calls the describe every time the handler is initialized. AWS Support have recommended to implement trying to save the log and catching the error response if the log stream/group doesn't exist, and then creating them if needed.

I will work on creating a PR for this issue, as we need the changes implemented.

**Comment by maxbanton** [comment]
Hi, Cameron!
Sounds reasonable.
I see few ways:
 - do DescribeLogGroups API call outside of Handler and cache it
 - use some kind of storage inside of Handler, which will add dependency on storage

From my prospective it's better to use second way.
Anyway, waiting for your PR. 
Let's show the the open source power!

Cheers!

**Comment by cjunge-work** [comment]
Unfortunately, we have decided to revert to standard file logging and let the AWS log agent transfer them to Cloudwatch. I don't think I'll have any time to make the changes.
