### ISSUE TITLE
Empty tags not allowed when creating LogGroup

### ISSUE THREAD

**Issue by holtkamp** [maxbanton/cwh#15]
When a LogGroup does not exist yet, it will be created. However, when no tags are used during instantiation of the CloudWatchLogsHandler, this results in the following error:

```
GuzzleHttp\Exception\ClientException: Client error: `POST https://logs.eu-west-1.amazonaws.com` resulted in a `400 Bad Request` response:
{"__type":"InvalidParameterException","message":"1 validation error detected: Value '{}' at 'tags' failed to satisfy in /app/project/vendor/aws/aws-sdk-php/src/WrappedHttpHandler.php on line 192
```
Two workarounds:
- do provide tags when instantiation of the CloudWatchLogsHandler
- commenting out the tags in the client

**Comment by maxbanton** [comment]
Should be fixed with https://github.com/maxbanton/cwh/pull/19
