### ISSUE TITLE
PHP fatal error 

### ISSUE THREAD

**Issue by banstola** [maxbanton/cwh#17]
I get fatal error when trying to push logs from my localhost

**Comment by banstola** [comment]
PHP Fatal error:  Uncaught exception 'Aws\CloudWatchLogs\Exception\CloudWatchLogsException' with message 'Error executing "DescribeLogGroups" on "https://logs.eu-west-1.amazonaws.com"; AWS HTTP error: Client error: `POST https://logs.eu-west-1.amazonaws.com` resulted in a `400 Bad Request` response:

**Comment by maxbanton** [comment]
Hi, @banstola!
Could you please provide next part of error message after `response:`?

**Comment by banstola** [comment]
Hi, that is all I have . That is the end of the sentence. I am trying to this for logging events in php lambda function having with nodejs wrapper

**Comment by banstola** [comment]
Hi, the token was optional parameter and it solves the problem. Maybe you should document it somewhere or remove the token part.
