### ISSUE TITLE
Extra array?

### ISSUE THREAD

**Issue by gracedigital** [maxbanton/cwh#22]
Great plugin, but i'm curious why there is an extra empty array that gets appended after submitting a log event.

For example... 
Request:
$message = "$i of $j - ($x)";
$this->log->info('Done saving record', [$message]);
Result:
INFO: Done saving record ["41158 of 129700 - (14801)"] []

What is that extra empty array at the end? Can it be populated? If so how?

**Comment by maxbanton** [comment]
Hi, @gracedigital!
Thanks for your question.
[Here](https://github.com/Seldaek/monolog/blob/master/doc/01-usage.md#adding-extra-data-in-the-records) you can find information about extra array.
If you do not use it, you can override default formatter like this
```php
use Monolog\Formatter\LineFormatter;
...
// Instantiate handler
$handler = new CloudWatch($client, 'php-logtest', 'ec2-instance-2', 1, 5);
// Instantiate formatter with template that contains no extra
$formatter = new LineFormatter("%level_name%: %message% %context%\n");
$handler->setFormatter($formatter);
```

Best regards,
Max.
