### ISSUE TITLE
Context is not searchable in cloudwatch

### ISSUE THREAD

**Issue by banstola** [maxbanton/cwh#23]
Hi, recently discovered that the context data provided as second argument to the logger's ```error``` or any other method   is not searchable in cloud watch. Only the message is searchable but no the context data.

**Comment by maxbanton** [comment]
Hi @banstola! 
I'm not sure if it's related to the handler.
You can use custom formatter and write your log entries without square brackets, just not to separate context from log entry message.

Kind regards, Max.

**Comment by banstola** [comment]
Hi Max,
Sorry my bad. It was a separate issue. Thanks for taking time to clarify this. Thank you again for a good work with this awesome handler though!

**Comment by maxbanton** [comment]
No problem, @banstola!
You are welcome!
