### ISSUE TITLE
Is it possible to set multi line log messages?

### ISSUE THREAD

**Issue by ankitsam** [maxbanton/cwh#30]
Is it possible to set multi line log messages? or able to set the parameter `multi_line_start_pattern` value?
Tried
`\r`
`\s`
`\n`

**Comment by marius-c** [comment]
Yeah. you must overwrite the line formatter:

`
$handler = new CloudWatch(...);
$handler->setFormatter(new LineFormatter("%level_name%: %message% %context% %extra%\n", null, true));
`
