### ISSUE TITLE
Cloudwatch logs 5 log events per second limit

### ISSUE THREAD

**Issue by nev7n** [maxbanton/cwh#4]
Hi,
thanks for writing this monolog handler, it's been really useful.  We've hit one issue with it - Cloudwatch logs has a [limit of 5 log events/second](http://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/cloudwatch_limits_cwl.html).

When our application exceeds this limit it causes an exception to be thrown:
```
Exception in run: Error executing "PutLogEvents" on "https://logs.us-east-1.amazonaws.com"; AWS HTTP error: Client error: `POST https://logs.us-east-1.amazonaws.com` resulted in a `400 Bad Request` response:
{
    "__type": "ThrottlingException",
    "message": "Rate exceeded"
}
ThrottlingException (client): Rate exceeded -
{
    "__type": "ThrottlingException",
    "message": "Rate exceeded"
}
[] []
```

Other cloudwatch agents get around this by internally buffering log events and then periodically sending batches of to the PutLogEvents API.  It would be great if this handler could do the same.

Justin.

**Comment by maxbanton** [comment]
Hi, @nev7n!
Are you using handler with Symfony application?

**Comment by nev7n** [comment]
Hi @maxbanton,
No it's a PHP command line script.

Justin (@nev7n)

**Comment by maxbanton** [comment]
Hi, @nev7n!
Is your command line script working as a daemon or it runs by cron?

**Comment by nev7n** [comment]
Hi Max,
the script is running in a docker container on AWS ECS(EC2 Container Service).  The docker container is launched by a cron job. 

This is the Dockerfile:-
```
FROM php:7

# Get dependencies
# zlib is needed for libpng which is used for png support in GD
# libxml2-dev is needed for php-soap which is needed for adwords API
RUN apt-get update \
    && apt-get install -y \
        curl \
        libssl-dev \
        zlib1g-dev \
        libpng-dev \
        libxml2-dev

# Install PHP extensions
RUN pecl install mongodb \
 && pecl install zip \
 && pecl install redis \
 && docker-php-ext-install zip \
 && docker-php-ext-enable mongodb \
 && docker-php-ext-enable redis \
 && docker-php-ext-install -j$(nproc) gd \
 && docker-php-ext-install soap

# Copy php.ini & command line php scripts into container
COPY ./cmd/php.ini /usr/local/etc/php
COPY ./cmd /home/cmd
RUN php /home/cmd/runImport.php
```

**Comment by maxbanton** [comment]
Hi, @nev7n!
Ok, will try to fix it.

**Comment by maxbanton** [comment]
Hi, @nev7n!
Issue is fixed with latest version of the library.
Update please and share results.
Thanks.

**Comment by nev7n** [comment]
Hi @maxbanton,
sorry for the slow reply - it's taken a while for us to get the new version of the library deployed to live.  Many thanks for implementing this change - it's fixed the over limit errors we were previously getting on CloudWatch.

The only issue we seem to be having is when we log less than the batch size the messages in the buffer don't seem to be written to cloudwatch after our script ends.  Is there anyway to flush the buffer at the end of our php script?  

Thanks,
nev7n

**Comment by maxbanton** [comment]
Hi @nev7n!
Buffer shoud be flushed automatically if application shutdowns correctly, I mean without die(); or so.
Monolog internal mechanism used for it.

Regards,
Max.
