### ISSUE TITLE
Flush everything in the queue

### ISSUE THREAD

**Issue by mahbubkabir** [maxbanton/cwh#52]
* **I'm submitting a ...**
  - [ X] feature request

* **Do you want to request a *feature* or report a *bug*?**
Feature

* **What is the current behavior?**
https://github.com/maxbanton/cwh/blob/master/src/Handler/CloudWatch.php#L149
It flushes the queue and then add the latest log/record in the queue. As a result there is alway something in the queue/buffer.
 
* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

* **What is the expected behavior?**
We should always add the new record to buffer and then do the checking. If the buffer size qualify the limit checking then it should flush everything.

* **What is the motivation / use case for changing the behavior?**
We are having some logs in the queue and when consumer dies we lose data
* **Please tell about your environment:**
  
  - PHP Version: 7.1
  - Operating system (distro): Linux
  - Application mode (web app / cli app / daemon cli app): Cli

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links to have context, eg. stackoverflow, etc)

**Comment by mahbubkabir** [comment]
It seems like I cannot create a branch to create a PR. Here is the solution 

`    /**
     * {@inheritdoc}
     */
    protected function write(array $record)
    {
        $records = $this->formatRecords($record);

        foreach ($records as $data) {
            $this->addToBuffer($data);

            if ($this->currentDataAmount >= $this->dataAmountLimit || count($this->buffer) >= $this->batchSize) {
                $this->flushBuffer();
            }
        }
    }`

**Comment by kiwinewt** [comment]
To flush the queue in a publicly accessible way I call $handler->close();

I looked into the source code and found it is literally..

    public function close()
    {
        $this->flushBuffer();
    }

**Comment by mahbubkabir** [comment]
We can close this as it's handle by Monolog now
