### ISSUE TITLE
Add a mechanism to handle SIGTERM/SIGINT/SIGUP

### ISSUE THREAD

**Issue by mahbubkabir** [maxbanton/cwh#53]
* **I'm submitting a ...**
  - [ ] feature request

* **Do you want to request a *feature* or report a *bug*?**
Feature
* **What is the current behavior?**
Unknown
* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

* **What is the expected behavior?**
When the script closes, it should send records to the AWS from the buffer
* **What is the motivation / use case for changing the behavior?**
Long running process
* **Please tell about your environment:**
  
  - PHP Version: 7.1
  - Operating system (distro): Linux
  - Application mode (web app / cli app / daemon cli app): Cli

        if (extension_loaded('pcntl')) {
            if (!function_exists('pcntl_signal')) {
                throw new \BadFunctionCallException("Function 'pcntl_signal' is referenced in the php.ini 'disable_functions' and can't be called.");
            }
            pcntl_signal(SIGTERM, array(&$this, 'close'));
            pcntl_signal(SIGINT, array(&$this, 'close'));
            pcntl_signal(SIGHUP, array(&$this, 'close'));
        }

**Comment by maxbanton** [comment]
Hi @mahbubkabir. I'm not sure that Monolog's extension shout take care on termination signals. 
Also, base class Handler which CloudWatch handler class extends has this code:
```public function __destruct()
    {
        try {
            $this->close();
        } catch (\Throwable $e) {
            // do nothing
        }
    }```

Regards, Max.
