### ISSUE TITLE
InvalidSequenceTokenException (client): The given sequenceToken is invalid. The next expected sequenceToken is

### ISSUE THREAD

**Issue by fs-kanayama** [maxbanton/cwh#55]
Hi

get a message `InvalidSequenceTokenException (client): The given sequenceToken is invalid. The next expected sequenceToken is...`

I am using asynchronous.
Problems occur when doing multiple asynchronous operations.

Is there an option that does not use tokens?

Thanks

**Comment by maxbanton** [comment]
Hi @fs-kanayama.
There are no possibility to not use sequenceTokens.
You can try to use different setup https://github.com/maxbanton/cwh/issues/28#issuecomment-396355601

Regards, Max.

**Comment by maxbanton** [comment]
Hi @fs-kanayama. Please try updated library version 1.1.10. InvalidSequenceTokenException should not appear anymore, thanks to @mstovicek.

**Comment by fs-kanayama** [comment]
Hi
I made an update
confirmed that the problem did not occur.
wonderful update.
Thanks.
