### ISSUE TITLE
Update Readme to mention actions required

### ISSUE THREAD

**Issue by b0ric** [maxbanton/cwh#59]
* **I'm submitting a ...**
  - [ ] bug report
  - [X] feature request
  - [ ] support request

* **Do you want to request a *feature* or report a *bug*?** Feature

* **What is the current behavior?**
List of a minimum set of required AWS IAM policy actions is not specified in the ReadMe

* **What is the expected behavior?**
Let's update ReadMe.md to mention a minimum set of CloudWatch IAM policy actions that have to be attached to a user.

* **What is the motivation / use case for changing the behavior?**
Many people prefer to create custom policies and specify only the actions that are necessary for an app to function. It took some time to figure out those that I was missing. 

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links to have context, eg. stackoverflow, etc):
Seems like this should be a complete list:
```
                "logs:CreateLogGroup",
                "logs:CreateLogStream",
                "logs:PutLogEvents",
                "logs:PutRetentionPolicy",
                "logs:DescribeLogStreams",
                "logs:DescribeLogGroups"
```

**Comment by maxbanton** [comment]
Hi @b0ric! PR from @zaaom was merged. Check it out https://github.com/maxbanton/cwh#aws-iam-needed-permissions
