### ISSUE TITLE
Long wait on async call, DescribeLogGroups

### ISSUE THREAD

**Issue by larxxor** [maxbanton/cwh#67]
* **I'm submitting a support request**
 
I see a peculiar behaviour, that may be intentional. I log to cloudwatch using Monolog and maxbanton/cwh

Most PHP request runs as expected, and complete in a timely manner.

But a few appear to take "forever" > 60 secs when monitoring in devops tools. I have yet to see it myself in the browser, it may not affect users.

When I analyze traces they are not actually doing anything, rather they are waiting on async http request initiated by Maxbanton\Cwh\Handler\CloudWatch::send

Is this expected behaviour?

---------
 
It happens like this, simplified, times are picked from actual example.

00.000s PHP request starts
00.183s Normal code finishes
00.183s Monolog\Handler\AbstractHandler::__destruct
00.183s Maxbanton\Cwh\Handler\CloudWatch::close
00.183s Maxbanton\Cwh\Handler\CloudWatch::flushBuffer
00.183s Maxbanton\Cwh\Handler\CloudWatch::send
00.183s Maxbanton\Cwh\Handler\CloudWatch::initialize
00.183s Aws\AwsClient::describeLogGroups
00.183s Aws\AwsClient::__call
.... GuzzleHttp working ...
0.190s GuzzleHttp\Promise\Promise::waitIfPending
65.502s Maxbanton\Cwh\Handler\CloudWatch::refreshSequenceToken
65.527s Aws\AwsClient::putLogEvents

**Comment by maxbanton** [comment]
HI @larxxor! 
That's unexpected behaviour, because this library does not call any asynchronous methods for AWS SDK.
Maybe something wrong with permissions or network.
Do you run your code on EC2/ECS instances?
