### ISSUE TITLE
Your requirements could not be resolved to an installable set of packages.

### ISSUE THREAD

**Issue by SteveWhyte** [maxbanton/cwh#72]
* **I'm submitting a ...**
  - [ ] bug report
  - [ ] feature request
  - [x] support request

* **Do you want to request a *feature* or report a *bug*?**

* **What is the current behavior?**

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Please tell about your environment:**
  
  - PHP Version:
  - Operating system (distro):
  - Application mode (web app / cli app / daemon cli app):

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links to have context, eg. stackoverflow, etc)

**Comment by SteveWhyte** [comment]
On a fresh Laravel install (v 6.3.0) unable to install package by composer.

I get the following issue with monolg version.

composer require maxbanton/cwh:^1.0
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for maxbanton/cwh 1.0 -> satisfiable by maxbanton/cwh[v1.0].
    - Conclusion: remove monolog/monolog 2.0.0
    - Conclusion: don't install monolog/monolog 2.0.0
    - maxbanton/cwh v1.0 requires monolog/monolog ^1.20 -> satisfiable by monolog/monolog[1.20.0, 1.21.0, 1.22.0, 1.22.1, 1.23.0, 1.24.0, 1.25.0, 1.25.1, 1.x-dev].
    - Can only install one of: monolog/monolog[1.20.0, 2.0.0].
    - Can only install one of: monolog/monolog[1.21.0, 2.0.0].
    - Can only install one of: monolog/monolog[1.22.0, 2.0.0].
    - Can only install one of: monolog/monolog[1.22.1, 2.0.0].
    - Can only install one of: monolog/monolog[1.23.0, 2.0.0].
    - Can only install one of: monolog/monolog[1.24.0, 2.0.0].
    - Can only install one of: monolog/monolog[1.25.0, 2.0.0].
    - Can only install one of: monolog/monolog[1.25.1, 2.0.0].
    - Can only install one of: monolog/monolog[1.x-dev, 2.0.0].
    - Installation request for monolog/monolog (locked at 2.0.0) -> satisfiable by monolog/monolog[2.0.0].


Installation failed, reverting ./composer.json to its original content.

**Comment by svoronuk** [comment]
Also will be helpful update aws-php to the latest version. 
In our project we update PHP to v7.3.10 and this [issue](https://github.com/guzzle/guzzle/pull/1686) was happened with guzzle. Trying to update guzzle raised conflict with aws-php version, but aws-php can not be updated, because of conflict with your library.

**Comment by d3radicated** [comment]
I tried to update the dependencies of this package in my fork [here](https://github.com/d3radicated/cwh). It now installs, it creates a group but it doesn't log (might be related to #65).

**Comment by kyokawasaki** [comment]
The problem seems to be an incompatibility with Monolog v2.0. If you downgrade Monolog to v1.20 you can install the dependency.
Haven't tested it yet tho

**Comment by maxbanton** [comment]
hi all!
Please check new release https://github.com/maxbanton/cwh/releases/tag/v2.0.0
