### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by syquus** [maxbanton/cwh#73]
* **I'm submitting a ...**
  - [ ] bug report
  - [ ] feature request
  - [X] support request

* **Do you want to request a *feature* or report a *bug*?**
More of a question
* **What is the current behavior?**
It is doing what it supposed to be, but adding a 35% of lag to each operation compared to not-using this library.

* **What is the expected behavior?**
Decrease the affected performance compared to not using this library.

* **Please tell about your environment:**
  
  - PHP Version: 7.2.25
  - Operating system (distro): Debian 8 y 9
  - Application mode (web app / cli app / daemon cli app): web app + cli app

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links to have context, eg. stackoverflow, etc)
We just made some comparison in our framework WITHOUT cwh and with it.

Times for a 100 requests with concurrency of 50, goes from 9 secs to 13 secs. Thats more than 33% of latency.

We made consistent tests to confirm this behaviour.

**Comment by maxbanton** [comment]
Hello @syquus .
This library uses AWS SDK, which uses AWS HTTP API, which have some limitations on requests amount.
Library tries to deal with limits on AWS side by adding sleep(1) in some cases, which can lead to additional latency of you app. 
If you need to log big amount of data, then you can try another solution such as logging to stdout and redirecting logs with fluentd.

Regards.
