### ISSUE TITLE
Allow Monolog 2.0

### ISSUE THREAD

**Issue by holtkamp** [maxbanton/cwh#76]
* **I'm submitting a ...**
  - [ ] bug report
  - [x] feature request

* **Do you want to request a *feature* or report a *bug*?**
Feature

* **What is the current behavior?**

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**
Allow to upgrade to Monolog 2.0

* **Please tell about your environment:**
  
  - PHP Version:
  - Operating system (distro):
  - Application mode:
    - [ ] Web app
    - [ ] CLI app
    - [ ] Daemon worker

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links to have context, eg. stackoverflow, etc)

Upgrade path seems quite straight forward: https://github.com/Seldaek/monolog/blob/master/UPGRADE.md

**Comment by maxbanton** [comment]
HI @holtkamp!
Please check new release https://github.com/maxbanton/cwh/releases/tag/v2.0.0

**Comment by holtkamp** [comment]
Wow @maxbanton that is some nice work you did there! Thanks a bunch and a happy 2020! 🎉
