### ISSUE TITLE
Question: is tagging suported?

### ISSUE THREAD

**Issue by yantolee** [maxbanton/cwh#8]
As the title said, am I able to use tagging when creating the loggroup? Thanks

**Comment by maxbanton** [comment]
Hi, @yantolee! 
Currently it's not supported, but I plan to implement it later.
Also, feel free to implement it by yourself and create pull request.

**Comment by maxbanton** [comment]
Hi, @yantolee!
Tagging is implemented in the latest version.
Please [take a look](https://github.com/maxbanton/cwh/releases/tag/v1.0)
