### ISSUE TITLE
[BUG] I get no errors, but no data is transferred to the Cloudwatch

### ISSUE THREAD

**Issue by sergeyantonuk** [maxbanton/cwh#94]
**Describe the bug**
I am trying to use this package in my laravel application.
My steps:
1. I created new group in IAM and added CloudwatchFullAccess policy
2. I created a user and added it to this group
3. After this I got Access key ID and Secret Access key
4. I installed package according to package documentation:
-  `composer require maxbanton/cwh:^2.0`
- next I added cloudwatch setings to my logging.php like here:
```
        'cloudwatch' => [
            'driver' => 'custom',
            'via' => \App\Logging\CloudWatchLoggerFactory::class,
            'sdk' => [
                'region' => env('AWS_DEFAULT_REGION', 'us-east-1'),
                'version' => 'latest',
                'credentials' => [
                    'key' => env('CLOUDWATCH_LOG_KEY'),
                    'secret' => env('CLOUDWATCH_LOG_SECRET')
                ]
            ],
            'retention' => env('CLOUDWATCH_LOG_RETENTION',7),
            'level' => env('CLOUDWATCH_LOG_LEVEL','info'),
            'stream' => env('CLOUDWATCH_STREAM', 'backend-log'),
        ],
```
- created factory class here: App/Logging/CloudWatchLoggerFactory.php
```
<?php

namespace App\Logging;

use Aws\CloudWatchLogs\CloudWatchLogsClient;
use Maxbanton\Cwh\Handler\CloudWatch;
use Monolog\Logger;

class CloudWatchLoggerFactory
{
    /**
     * Create a custom Monolog instance.
     *
     * @param  array  $config
     * @return \Monolog\Logger
     */
    public function __invoke(array $config)
    {
        $sdkParams = $config["sdk"];
        $tags = $config["tags"] ?? [ ];
        $name = $config["name"] ?? 'cloudwatch';

        // Instantiate AWS SDK CloudWatch Logs Client
        $client = new CloudWatchLogsClient($sdkParams);

        // Log group name, will be created if none
        $groupName = config('app.name') . '-' . config('app.env');

        // Log stream name, will be created if none
        $streamName = config('app.hostname');

        // Days to keep logs, 14 by default. Set to `null` to allow indefinite retention.
        $retentionDays = $config["retention"];

        // Instantiate handler (tags are optional)
        $handler = new CloudWatch($client, $groupName, $streamName, $retentionDays, 10000, $tags);

        // Create a log channel
        $logger = new Logger($name);
        // Set handler
        $logger->pushHandler($handler);

        return $logger;
    }
}
```
- Next I used this in my index controller:  `Log::info('Test CloudWatch');`
- added `LOG_CHANNEL=cloudwatch `to my .env
I get no errors, but no data is transferred to the Cloudwatch. Also a Log group is created on Cloudwatch side, but the log streams is empty.
What I did wrong?

**Expected behavior**
1. create new group in IAM and added CloudwatchFullAccess policy
2. create new user and add into this group
3. install package according to package documentation
4. switch to cloudwatch channel in your .env 
5. when you run  Log::info() in your code logging data should be transmitted to Cloudwatch

**Please tell about your environment:**
   Laravel Version: v7.19.1
   PHP Version: v7.2.24
   Ubuntu 18.04.3 LTS
  - Application mode:
     Web app

**Comment by posglobalcadev** [comment]
I'm having the same problem too

Laravel: 8.27.0
PHP Version: 7.3.22 (XAMPP)
Windows 10 Pro 20H2

**Comment by marcmascort** [comment]
> Suitable for web applications and for long-living CLI daemons and workers

This library is performed for long-living, and only send records if buffer is full. If you want send immediately set `batch_size` to **1** in `logging.php` (By default is 10000)

Example:
```
        'cloudwatch' => [
            'driver' => 'custom',
            'via' => \App\Logging\CloudWatchLoggerFactory::class,
            'sdk' => [
                'region' => env('AWS_DEFAULT_REGION', 'us-east-1'),
                'version' => 'latest',
                'credentials' => [
                    'key' => env('CLOUDWATCH_LOG_KEY'),
                    'secret' => env('CLOUDWATCH_LOG_SECRET')
                ]
            ],
            'retention' => env('CLOUDWATCH_LOG_RETENTION',7),
            'level' => env('CLOUDWATCH_LOG_LEVEL','info'),
            'stream' => env('CLOUDWATCH_STREAM', 'backend-log'),
            'batch_size' => 1,
        ],
```

**Comment by joshmakar** [comment]
@sergeyantonuk Were you able to resolve your issue? I'm running into the exact same problem.

**Comment by jpvdpoel** [comment]
@sergeyantonuk I'm having the exact same problem as well. Above suggestion (changing batch_size) did not work. The Log Group is created, but there's no stream.

**Comment by sergeyantonuk** [comment]
Sorry guys for the late reply.
Yes I had the same problem, the `$streamName` was NULL in  `CloudWatchLoggerFactory.php`, because I did not have a `hostname` in my `app.php`
It's just a rushed mistake, so we can close this issue
